repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # standard end of line/end of file cleanup
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # ensure syntaxes are valid
      - id: check-toml
      - id: check-yaml
      - id: check-json
      # catch git merge/rebase problems
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        types_or: [python]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.15.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
        types_or: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        types_or: [python]
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        args: [--exit-zero]
        types_or: [python]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [--exit-zero]
        types_or: [python]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types_or: [ts]
