name: Automate Boards
on:
  issues:
    types: [opened, labeled, unlabeled]
  project_card:
    types: [created, deleted]
env:
  BACKLOG_LBL: backlog
  SPRINT_LBL: sprint
  # these variables cannot be used in if expressions
  # see https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
  TRIAGING_ID: 4
  TRIAGING_URL: https://api.github.com/projects/13697310
  BACKLOG_ID: 5
  BACKLOG_URL: https://api.github.com/projects/13697370
  SPRINT_ID: 8
  SPRINT_URL: https://api.github.com/projects/13829490
jobs:
  # (helper) get issue number
  issue:
    outputs:
      number: >-
        ${{
          steps.number.outputs.replaced
          || github.event.issue.number
        }}
      id: >-
        ${{
          steps.id.outputs.replaced
          || github.event.issue.id
        }}
    runs-on: ubuntu-latest
    steps:
      - name: url
        if: github.event_name == 'project_card'
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: https://api.github.com(/.+)
          string: ${{ github.event.project_card.content_url }}
          replace-with: $1
      - name: request
        if: github.event_name == 'project_card'
        uses: octokit/request-action@v2.1.0
        with:
          route: GET ${{ steps.url.outputs.replaced }}
      - name: number
        run: echo "::set-output number=${{ fromJSON(steps.request.outputs.data)['number'] }}"
      - name: id
        run: echo "::set-output id=${{ fromJSON(steps.request.outputs.data)['id'] }}"

  # (helper) whether issue is on Triaging/Sprint board
  project:
    needs: issue
    outputs:
      on_triaging: >-
        ${{
          steps.on_triaging.outputs.contains
          || github.event.project_card.project_url == env.TRIAGING_URL
        }}
      on_sprint: >-
        ${{
          steps.on_sprint.outputs.contains
          || github.event.project_card.project_url == env.SPRINT_URL
        }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: on_triaging
        if: github.event_name == 'issues'
        uses: ./.github/actions/project-has-issue
        with:
          org: conda
          project: ${{ env.TRIAGING_ID }}
          issue: ${{ needs.issue.outputs.id }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
      - name: on_sprint
        if: github.event_name == 'issues'
        uses: ./.github/actions/project-has-issue
        with:
          org: conda
          project: ${{ env.SPRINT_ID }}
          issue: ${{ needs.issue.outputs.id }}
          github_token: ${{ secrets.PROJECT_TOKEN }}

  # new -> Triaging[New]
  to_triaging:
    # if new issue and not [backlog] or [sprint]
    if: >-
      github.event_name == 'issues'
      && github.event.action == 'opened'
      && !contains(github.event.issue.labels.*.name, 'backlog')
      && !contains(github.event.issue.labels.*.name, 'sprint')
    runs-on: ubuntu-latest
    steps:
      # add to Triaging board
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          action: add # if not present
          project: Triaging
          column: New
          repo-token: ${{ secrets.PROJECT_TOKEN }}

  # new -> Backlog[Unplanned]
  # Triaging[Ready] -> Backlog[Unplanned]
  # Sprint[To Do] -> Backlog[Do Next]
  to_backlog:
    # if new issue with [backlog]
    # if labeled [backlog]
    # if added to Backlog board
    # if unlabeled [sprint]
    # if removed from Sprint board
    if: >-
      github.event.issue.state == 'open' && (
        (
          github.event_name == 'issues'
          && github.event.action == 'opened'
          && contains(github.event.issue.labels.*.name, 'backlog')
          && !contains(github.event.issue.labels.*.name, 'sprint')
        )
        || (
          github.event_name == 'issues'
          && github.event.action == 'labeled'
          && github.event.label.name == 'backlog'
        )
        || (
          github.event_name == 'project_card'
          && github.event.action == 'created'
          && github.event.project_card.project_url == 'https://api.github.com/projects/13697370'
          && !github.event.project_card.note
          && github.event.project_card.content_url
        )
        || (
          github.event_name == 'issues'
          && github.event.action == 'unlabeled'
          && github.event.label.name == 'sprint'
        )
        || (
          github.event_name == 'project_card'
          && github.event.action == 'deleted'
          && github.event.project_card.project_url == 'https://api.github.com/projects/13829490'
          && !github.event.project_card.note
          && github.event.project_card.content_url
        )
      )
    needs: [issue, project]
    runs-on: ubuntu-latest
    steps:
      # (fail-safe) remove from Triaging board
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          action: delete # if present
          project: Triaging
          column: Ready # unused
          repo-token: ${{ secrets.PROJECT_TOKEN }}
      # add [backlog] label
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: ${{ env.BACKLOG_LBL }}
          number: ${{ needs.issue.outputs.number }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
      # add to Backlog board (from Triaging board)
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: >-
          fromJSON(needs.project.outputs.on_triaging) || (
            !contains(github.event.issue.labels.*.name, 'sprint')
            && !fromJSON(needs.project.outputs.on_sprint)
          )
        with:
          action: add # if not present
          project: Backlog
          column: Unplanned
          repo-token: ${{ secrets.PROJECT_TOKEN }}
      # add to Backlog board (from Sprint board)
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: >-
          !fromJSON(needs.project.outputs.on_triaging) && (
            contains(github.event.issue.labels.*.name, 'sprint')
            || fromJSON(needs.project.outputs.on_sprint)
          )
        with:
          action: add # if not present
          project: Backlog
          column: Do Next
          repo-token: ${{ secrets.PROJECT_TOKEN }}
      # remove [sprint] label
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: ${{ env.SPRINT_LBL }}
          number: ${{ needs.issue.outputs.number }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
      # remove from Sprint board
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          action: delete # if present
          project: Sprint
          column: To Do # unused
          repo-token: ${{ secrets.PROJECT_TOKEN }}

  # new -> Sprint[To Do]
  # Backlog[Do Next] -> Sprint[To Do]
  to_sprint:
    # if new issue with [sprint]
    # if unlabeled [backlog]
    # if removed from Backlog board
    # if labeled [sprint]
    # if added to Sprint board
    if: >-
      github.event.issue.state == 'open' && (
        (
          github.event_name == 'issues'
          && github.event.action == 'opened'
          && contains(github.event.issue.labels.*.name, 'sprint')
        )
        || (
          github.event_name == 'issues'
          && github.event.action == 'unlabeled'
          && github.event.label.name == 'backlog'
        )
        || (
          github.event_name == 'project_card'
          && github.event.action == 'deleted'
          && github.event.project_card.project_url == 'https://api.github.com/projects/13697370'
          && !github.event.project_card.note
          && github.event.project_card.content_url
        )
        || (
          github.event_name == 'issues'
          && github.event.action == 'labeled'
          && github.event.label.name == 'sprint'
        )
        || (
          github.event_name == 'project_card'
          && github.event.action == 'created'
          && github.event.project_card.project_url == 'https://api.github.com/projects/13829490'
          && !github.event.project_card.note
          && github.event.project_card.content_url
        )
      )
    needs: issue
    runs-on: ubuntu-latest
    steps:
      # (fail-safe) remove from Triaging board
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          action: delete # if present
          project: Triaging
          column: Ready # unused
          repo-token: ${{ secrets.PROJECT_TOKEN }}
      # remove [backlog] label
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: ${{ env.BACKLOG_LBL }}
          number: ${{ needs.issue.outputs.number }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
      # remove from Backlog board
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          action: delete # if present
          project: Backlog
          column: Do Next # unused
          repo-token: ${{ secrets.PROJECT_TOKEN }}
      # add [sprint] label
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: ${{ env.SPRINT_LBL }}
          number: ${{ needs.issue.outputs.number }}
          github_token: ${{ secrets.PROJECT_TOKEN }}
      # add to Sprint board
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          action: add # if not present
          project: Sprint
          column: To Do
          repo-token: ${{ secrets.PROJECT_TOKEN }}
