name: Recent
on:
  schedule:
    # on the hour, every hour
    # https://crontab.guru/#0_*_*_*_*
    - cron: 0 * * * *
jobs:
  recent:
    if: >-
      !github.event.repository.fork
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      # run query
      - run: node snapshots.js recent 72
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Hourly snapshot
          commit_user_name: Conda Bot
          commit_user_email: 18747875+conda-bot@users.noreply.github.com
          commit_author: Conda Bot <18747875+conda-bot@users.noreply.github.com>
